// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEizjoYOwxCtvTS0GkzUp2FgpDdvtIXoQ',
    appId: '1:958558397711:web:ceceda1490510b4ed6ca7a',
    messagingSenderId: '958558397711',
    projectId: 'ecommerceapp-c0d83',
    authDomain: 'ecommerceapp-c0d83.firebaseapp.com',
    databaseURL: 'https://ecommerceapp-c0d83-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-c0d83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJrhlvH3SHx3YF7aA6TgRbZpcuBx5zjg',
    appId: '1:958558397711:android:3f5155599aa75f32d6ca7a',
    messagingSenderId: '958558397711',
    projectId: 'ecommerceapp-c0d83',
    databaseURL: 'https://ecommerceapp-c0d83-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-c0d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmtZBsvt_9LReoQMDpul5TDNW_d6QoEw',
    appId: '1:958558397711:ios:66662b7db15d4b95d6ca7a',
    messagingSenderId: '958558397711',
    projectId: 'ecommerceapp-c0d83',
    databaseURL: 'https://ecommerceapp-c0d83-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-c0d83.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmtZBsvt_9LReoQMDpul5TDNW_d6QoEw',
    appId: '1:958558397711:ios:cef9cfc79b349869d6ca7a',
    messagingSenderId: '958558397711',
    projectId: 'ecommerceapp-c0d83',
    databaseURL: 'https://ecommerceapp-c0d83-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-c0d83.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
